version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: bytebattle-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: bytebattle
      POSTGRES_USER: bytebattle
      POSTGRES_PASSWORD: bytebattle

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bytebattle -d bytebattle"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
