name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: ${{ secrets.PG_USER_TEST }}
      DB_PASSWORD: ${{ secrets.PG_PASSWORD_TEST }}
      DB_NAME: ${{ secrets.PG_DB_TEST }}

    services:
      postgres:
        image: postgres:18-alpine
        env:
          POSTGRES_USER: ${{ secrets.PG_USER_TEST }}
          POSTGRES_PASSWORD: ${{ secrets.PG_PASSWORD_TEST }}
          POSTGRES_DB: ${{ secrets.PG_DB_TEST }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install tools
        run: |
          go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@v4.19.1
          go install github.com/jstemmer/go-junit-report/v2@v2.1.0

      - name: Run database migrations
        run: migrate -path ./migrations -database "postgres://$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME?sslmode=disable" up

      - name: Create sqlboiler config
        run: |
          cat > sqlboiler.toml << EOF
          [psql]
            host = "${{ env.DB_HOST }}"
            port = ${{ env.DB_PORT }}
            user = "${{ secrets.PG_USER_TEST }}"
            pass = "${{ secrets.PG_PASSWORD_TEST }}"
            dbname = "${{ secrets.PG_DB_TEST }}"
            sslmode = "disable"
          EOF

      - name: Generate SQLBoiler models
        run: make generate

      - name: Lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.9.0

      - name: Build
        run: go build ./...

      - name: Run tests
        run: |
          go test -v -json ./cmd/... ./internal/config/... ./internal/server/... ./internal/service/... ./internal/database 2>test-stderr.log | tee test-output.json | go-junit-report -set-exit-code > report.xml

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: go-test-report
          retention-days: 7
          path: |
            report.xml
            test-output.json
            test-stderr.log
